databases:
  - name: go_levi_db
    plan: free
    databaseName: go_levi_db
    user: go_levi_db_user

services:
  - type: web
    plan: free
    name: golevi
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn levi.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: go-levi-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4